---
title: "R Scrapping"
author: "Dessy Rotua Natalina Siahaan"
date: '2022-06-23'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(rvest)
library(stringr)
```
-- Scraping --

```{r}
url <- "https://www.bi.go.id/en/statistik/informasi-kurs/jisdor/Default.aspx"
html <- url %>% read_html
```

```{r}
jisdor <- html %>%
    html_node(".table-lg") %>% #table-lg
    html_table

str(jisdor)
jisdor
```

```{r}
today <- format(Sys.time(), "%d")
jisdor$Day <- unlist(lapply(str_split(jisdor$Date, " "), `[[`, 1))
newdate <- jisdor[which(jisdor$Day==today),]
```

-- Connect to MongoDB --


```{r}
connection_string = 'mongodb+srv://dbmds001:sta562mds@STAMDS.kuzgp.mongodb.net/?retryWrites=true&w=majority'
kurs_bi = mongo(collection="kurs_jisdor",
                         db="bot_kurs",
                         url=connection_string)
```

-- Insert Data to MongoDB --
```{r}
kurs_bi$insert(newdate)
```
